version: '3'
services:
  projectname-backend:
    build: .
    ports:
      - "19998:5000"
    depends_on:
      - postgres
  projectname-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: obugs
      POSTGRES_USER: obugs
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../projectname_postgres_data:/var/lib/postgresql/data
