version: '3'
services:
  db:
    image: postgres:latest
    container_name: template-backend-dev-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: obugs
      POSTGRES_USER: obugs
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ../../obugs_postgres_data:/var/lib/postgresql/data